[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "flit_core >=2,<3"]

[tool.black]
line-length = 99
target-version = ['py311']


[project]
requires = [
  "questionary==2.0.1"
]