[build-system]
requires = ["setuptools>=61.0.0", "wheel", 'questionary==2.0.1']
build-backend = "setuptools.build_meta"

[project]
name = "job_queue"
version = "0.0.1"
description = "A minimal Request Manager for an assignment in backend job position"
readme = "README.md"
authors = [
    { name = "vahidtwo", email = "vahidtwo@gmail.com" },
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = []

requires-python = ">=3.10"

[project.optional-dependencies]
build = ["build", "twine", "bumpver"]


[project.urls]
repository = "https://github.com/vahidtwo/minimal_request_manager"


[tool.bumpver]
current_version = "0.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]